# Generated by Django 5.0.6 on 2024-08-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_rename_user_perfil_usuario_alter_perfil_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
    ]
