# Generated by Django 5.0.6 on 2024-08-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_rename_usuario_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('normal', 'Normal'), ('owner', 'Owner')], default='normal', max_length=10),
        ),
    ]
