# Generated by Django 5.0.6 on 2024-08-16 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_publicacion_likes_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='modelo',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='descripcion_corta',
            field=models.CharField(default='Descripción por defecto', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_publicaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
