# Generated by Django 5.0.6 on 2024-08-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_remove_publicacion_likes_remove_publicacion_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
