# Generated by Django 5.0.6 on 2024-08-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_publicacion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='apellido_autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='nombre_autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
